apiVersion: apps/v1
kind: Deployment
metadata:
  name: created-issues-microservice-blue
  namespace: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-blue
  template:
    metadata:
      labels:
        app: microservices-blue
    spec:
      containers:
        - name: created-issues-microservice
          image: 438911158232.dkr.ecr.ap-south-1.amazonaws.com/created_issues_instance:latest
          ports:
            - containerPort: 8081