apiVersion: v1
kind: Service
metadata:
  name: microservices-service-blue
  namespace: blue
spec:
  selector:
    app: microservices-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: created-issues-microservice-service-blue
  namespace: blue
spec:
  selector:
    app: microservices-blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer