apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: created-issues-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_issues_instance:latest
          ports:
            - containerPort: 8081
        - name: closed-issues-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/closed_issues_instance:latest
          ports:
            - containerPort: 8082
        - name: created-commits-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_commits_instance:latest
          ports:
            - containerPort: 8083
        - name: created-prs-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_prs_instance:latest
          ports:
            - containerPort: 8084