apiVersion: apps/v1
kind: Deployment
metadata:
  name: created-issues-microservice-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-green
  template:
    metadata:
      labels:
        app: microservices-green
    spec:
      containers:
        - name: created-issues-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_issues_instance:latest
          ports:
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: closed-issues-microservice-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-green
  template:
    metadata:
      labels:
        app: microservices-green
    spec:
      containers:
        - name: closed-issues-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/closed_issues_instance:latest
          ports:
            - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: created-commits-microservice-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-green
  template:
    metadata:
      labels:
        app: microservices-green
    spec:
      containers:
        - name: created-commits-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_commits_instance:latest
          ports:
            - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: created-prs-microservice-green
  namespace: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-green
  template:
    metadata:
      labels:
        app: microservices-green
    spec:
      containers:
        - name: created-prs-microservice
          image: ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_prs_instance:latest
          ports:
            - containerPort: 8084