apiVersion: v1
kind: Service
metadata:
  name: microservices-service-green
  namespace: green
spec:
  selector:
    app: microservices-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: created-issues-microservice-service-green
  namespace: green
spec:
  selector:
    app: microservices-green
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: closed-issues-microservice-service-green
  namespace: green
spec:
  selector:
    app: microservices-green
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: created-commits-microservice-service-green
  namespace: green
spec:
  selector:
    app: microservices-green
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: created-prs-microservice-service-green
  namespace: green
spec:
  selector:
    app: microservices-green
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer