name: DeveloperIQ
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Created Issues Microservice Docker image
      run: |
        docker build -t created_issues_microservice_image created_issues_microservice/
        docker tag created_issues_microservice_image:latest ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_issues_instance:latest
        docker push ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_issues_instance:latest
    - name: Build and Push Closed Issues Microservice Docker image
      run: |
        #docker build -t closed_issues_microservice_image closed_issues_microservice/
        #docker tag closed_issues_microservice_image:latest ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/closed_issues_instance:latest
        #docker push ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/closed_issues_instance:latest
    - name: Build and Push Created Commits Microservice Docker image
      run: |
        #docker build -t created_commits_microservice_image created_commits_microservice/
        #docker tag created_commits_microservice_image:latest ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_commits_instance:latest
        #docker push ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_commits_instance:latest
    - name: Build and Push Created PRs Microservice Docker image
      run: |
        #docker build -t created_prs_microservice_image created_prs_microservice/
        #docker tag created_prs_microservice_image:latest ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_prs_instance:latest
        #docker push ${{ secrets.AWS_INSTANCE_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/created_prs_instance:latest

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name developer-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f blue-namespace.yaml
        kubectl apply -f blue-deployment.yaml
        kubectl apply -f blue-service.yaml